version: 2
accept_configuration:
  condition: property
  property: host.osVersion
  in_values: [Ubuntu_22_04, Ubuntu_24_04]



instructions:
  Build:
    - type: EnvironmentVariable
      variableName: NON_QTBASE_CMAKE_ARGS
      variableValue: "{{.Env.NON_QTBASE_CMAKE_ARGS}} -DCMAKE_INSTALL_PREFIX:PATH=/home/qt/work/install -DBUILD_TESTING=OFF"
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test: []
