version: 2
accept_configuration:
  condition: property
  property: host.osVersion
  in_values: [Ubuntu_22_04, Ubuntu_24_04]

Configurations:
  - Template: 'qtci-linux-Ubuntu-22.04-x86_64-51'
    Compiler: 'GCC'
    Features: ['DisableTests']

instructions:
  Build:
    - !include "{{qt/qtbase}}/coin_module_build_template_v2.yaml"

  Test: []
